kind: Deployment
apiVersion: apps/v1
metadata:
  name: nano-gpu-scheduler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nano-gpu-scheduler
  template:
    metadata:
      labels:
        app: nano-gpu-scheduler
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccount: nano-gpu
      containers:
        - name: nano-gpu-scheduler
          image: nano-gpu/nano-gpu-scheduler
          command: ["/usr/bin/nano-gpu-scheduler"]
          args: ["--priority", "binpack", "--v", "2"]
          env:
            - name: PORT
              value: "39999"
---
apiVersion: v1
kind: Service
metadata:
  name: nano-gpu-scheduler
  namespace: kube-system
  labels:
    app: nano-gpu-scheduler
spec:
  ports:
    - port: 39999
      targetPort: 39999
  selector:
    app: nano-gpu-scheduler
